// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy7ef_PX5yRfWlPpJEaPP84JY6O2QImWo',
    appId: '1:667924120080:web:23fabd4e1bc269b3bdc095',
    messagingSenderId: '667924120080',
    projectId: 'inventario-de053',
    authDomain: 'inventario-de053.firebaseapp.com',
    storageBucket: 'inventario-de053.firebasestorage.app',
    measurementId: 'G-F86VHT5ZW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM-QwRdTamfaRCqViywCfvAg8qwT4DsjE',
    appId: '1:667924120080:android:12e71df7f968460ebdc095',
    messagingSenderId: '667924120080',
    projectId: 'inventario-de053',
    storageBucket: 'inventario-de053.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOApoHzxRYmDqinq4q0T_ppokMKhHqg64',
    appId: '1:667924120080:ios:265209be415469e5bdc095',
    messagingSenderId: '667924120080',
    projectId: 'inventario-de053',
    storageBucket: 'inventario-de053.firebasestorage.app',
    iosBundleId: 'com.eamc.inventario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOApoHzxRYmDqinq4q0T_ppokMKhHqg64',
    appId: '1:667924120080:ios:265209be415469e5bdc095',
    messagingSenderId: '667924120080',
    projectId: 'inventario-de053',
    storageBucket: 'inventario-de053.firebasestorage.app',
    iosBundleId: 'com.eamc.inventario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy7ef_PX5yRfWlPpJEaPP84JY6O2QImWo',
    appId: '1:667924120080:web:806d1eaf938e4ba9bdc095',
    messagingSenderId: '667924120080',
    projectId: 'inventario-de053',
    authDomain: 'inventario-de053.firebaseapp.com',
    storageBucket: 'inventario-de053.firebasestorage.app',
    measurementId: 'G-EYLEQNBNS5',
  );
}
